---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

# Bar chart of instacart

```{r plotly}

set.seed(1)

data("instacart")

insta_plotly =
  instacart %>% 
  sample_n(30000) 

insta_plotly %>% 
  group_by(department) %>% 
  arrange(desc(order_hour_of_day)) %>% 
  plot_ly(x = ~department, y = ~order_hour_of_day)
#, type = "bar", color = ~order_hour_of_day)

insta_plotly %>% 
  count(department) %>% 
  mutate(aisle = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, type = "bar", color = ~department)
  
#insta_plotly %>% 
 # group_by(department) %>% 
  #count(department) %>% 
   #plot_ly(
    #x = ~order_hour_of_day, y = ~n, type = "scatter", mode = "markers",
    #color = ~department, text = ~text_label, alpha = 0.5)

str(insta_plotly)
```

```{r}
insta_plotly %>% 
  group_by(department) %>% 
  plot_ly(y = ~order_number, color = ~department, type = "box",
          colors = "Set2")
```



